language: node_js
node_js:
  - "11.1.0"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm i nauchikus/typescript-definitive-guide#whats-is-new-builder
  - npm i cross-env

script:
  - sh build.sh

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: dest/
  on:
    branch: master